import Head from "next/head";
import { Footer } from "../footer";
interface LayoutProps {
  children: React.ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <div className="relative">
      <Head>
        <title>Flashcard App</title>
        <meta name="description" content="Generated by Flashcard App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
      {/* <img
        src="./gradient-left-dark.svg"
        className="block fixed bottom-0 -right-1/3 w-full h-full z-0"
        alt="background-dark"
      />
      <img
        src="./gradient-right-dark.svg"
        className="block fixed bottom-0 right-1/3 w-full h-full z-0"
        alt="background-dark"
      /> */}
      <Footer />
    </div>
  );
};

export default Layout;
