import Head from "next/head";
import { ReactElement } from "react";
import  GlobalLayout  from "../components/layout/global";
import React from "react";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Flashcard App</title>
        <meta name="description" content="Generated by Flashcard App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <GlobalLayout>{page}</GlobalLayout>
};

export default Home;
